[versions]
minSdk = "24"
targetSdk = "33"

kotlin-gradle-plugin = "1.8.10"
android-gradle-plugin = "8.0.1"
maven-gradle-plugin = "2.1"

androidx-core-ktx = "1.8.0"
androidx-appcompat = "1.5.1"
androidx-activity-compose = "1.4.0"
androidx-navigation-compose = "2.5.3"
androidx-constraintlayout-compose = "1.0.1"
androidx-datastore = "1.0.0"

compose-ui = "1.4.3"
compose-foundation = "1.4.3"
compose-material = "1.4.3"
compose-compiler = "1.4.4"

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout-compose" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-foundation" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-material" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
compoes-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
compoes-compiler = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }

maven-gradle-plugin = { module = "com.github.dcendents:android-maven-gradle-plugin", version.ref = "maven-gradle-plugin"}